name: CI
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: [ es365, self-hosted]
    env:
      IMAGE_NAME: es365-backend
    steps:
      - uses: actions/checkout@v3
      - name: Add package repository
        uses: actions/setup-node@v4
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
  deploy:
    runs-on: self-hosted
    needs: build
    env:
      IMAGE_NAME: es365-backend
    steps:
      - uses: actions/checkout@v4
      - name: Add package repository
        uses: actions/setup-node@v4
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 --name my-container ${{ env.IMAGE_NAME }}:latest
          echo "Container is running on port 8080"
       