name: CI
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    env:
      REGISTRY: cr.selcloud.ru
      IMAGE_NAME: cr.selcloud.ru/test-registry/${{ github.repository }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Add package repository
        uses: actions/setup-node@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: token
          password: CRgAAAAAZSoV3DqNwT5f65ZM1SNMgYUwT5jIcuO4

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
  deploy:
    runs-on: self-hosted
    needs: build
    env:
      IMAGE_NAME: cr.selcloud.ru/test-registry/${{ github.repository }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Add package repository
        uses: actions/setup-node@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: token
          password: CRgAAAAAZSoV3DqNwT5f65ZM1SNMgYUwT5jIcuO4
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 --name danocher/es365-back ${{ env.IMAGE_NAME }}:latest
          echo "Container is running on port 8080"
       